require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'tmp/*'
    - 'vendor/*'
    - 'log/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/*'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'db/*'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'db/*'

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/HashAlignment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'

Style/Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
